### ISSUE TITLE
Troubleshooting steps

### ISSUE THREAD

**Issue by cverbiest** [KiltedKanuck/OpenEdgeOtelClient#1]
still trying to get the workshop sample working.

got this test working
https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/get-started/opentelemetry-tutorial-python/#pre-instrum

will update this issue if I find more info

**Comment by cverbiest** [comment]
I got it working

## working config.yml
I don't think that apart from the EU endpoint address there is any significant diffrence with the one you mailed during the session.


```
receivers: 
  otlp:
    protocols:
      grpc:
      http:        
  otlp/withendpoint:
    protocols:
        grpc:
            endpoint: localhost:4317
        http:
            endpoint: localhost:4318

exporters:
  logging:
     verbosity: detailed
  file:
    path: ./results.json
  otlp: 
    endpoint: otlp.eu01.nr-data.net:4317
    headers:
        api-key: **********************************************
  
processors:
  batch:
service:
  telemetry:
    logs:
      level: "debug"
  pipelines:
    traces:
      receivers: [otlp, otlp/withendpoint]
      exporters: [otlp, file, logging]
      #exporters: [file, logging]
    metrics:
      receivers: [otlp, otlp/withendpoint]
      exporters: [otlp, file, logging]
      #exporters: [otlp,logging,file]

```
